### ISSUE TITLE
ReadMe outdated and broken links

### ISSUE THREAD

**Issue by teadetime** [pybind/pybind11_abseil#10]
`PYBIND11_ABSEIL_STATUS_MODULE_PATH` Does not seem to exist in [status_casters.h](https://github.com/pybind/pybind11_abseil/blob/master/pybind11_abseil/status_casters.h)

This seems to make https://github.com/pybind/pybind11_abseil#use-outside-of-google3 irrelevant?

Additionally the "it's documentation" link in https://github.com/pybind/pybind11_abseil#importing-the-status-module is broken.

**Comment by rwgk** [comment]
Thanks for pointing this out. Fixed with ba421f1152cfc06db1a65c0768886ef55822b1d5.
